name: aquarium

services:
  app:
    build: ./services/api_bus
    depends_on:
      - db
    volumes:
      - ./services/api_bus:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - .env
    ports:
      - '127.0.0.1:8000:8000'
      - '127.0.0.1:8001:8001'

  db:
    image: pgvector/pgvector:pg16
    container_name: data_base
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - .env
    ports:
      - '127.0.0.1:5432:5432'

volumes:
  postgres_data:
