components_manager:
  task_processors:
    main-task-processor:
      worker_threads: 4
    fs-task-processor:
      worker_threads: 1

  default_task_processor: main-task-processor

  components:
    server:
      listener:
        port: 8080
        task_processor: main-task-processor

    logging:
      loggers:
        default:
          file_path: '@stderr'
          level: debug
          overflow_behavior: discard

    dynamic-config:

    testsuite-support:

    grpc-server:
      port: 8081

    grpc-client-factory:

    grpc-client-common:
      blocking-task-processor: main-task-processor

    grpc-client-middlewares-pipeline:
      load-enabled: true

    health-service:
      health-prefix: "aquarium"
      task-processor: main-task-processor

    user-store-client:
      endpoint: "127.0.0.1:8081"

    user-store-service:
      task-processor: main-task-processor
      invite_key: "secret_invite_key_value"

    postgres-db:
      dbconnection: $pg_connection
      blocking_task_processor: fs-task-processor
      dns_resolver: async
      sync-start: true

    dns-client:
      fs-task-processor: fs-task-processor
